DROP TABLE MUSER;

CREATE TABLE MUSER(
ID VARCHAR2(50) PRIMARY KEY,
PASSWORD VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
NICKNAME VARCHAR2(50) NOT NULL,
PHONE VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
ROLE VARCHAR2(10) NOT NULL,
ENABLED VARCHAR2(2) NOT NULL,

CONSTRAINT CHECK_ROLE CHECK(ROLE IN('ADMIN','USER')),
CONSTRAINT CHECK_ENABLED CHECK(ENABLED IN('Y','N'))
);

INSERT INTO MUSER VALUES('ADMIN01','1234','최명서','햄토리','010-1234-5678','myeongseo@naver.com','ADMIN','Y');
INSERT INTO MUSER VALUES('USER01','1234','A','APPLE','010-1234-5678','APPLE@naver.com','USER','Y');

SELECT * FROM MUSER;

SELECT PASSWORD FROM MUSER WHERE ID = 'ADMIN01' AND ENABLED='Y';